# fly.toml app configuration file generated for imusic on 2026-04-20T16:35:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'imusic'
primary_region = 'ord'

[build]
  dockerfile = "Dockerfile"

[env]
  WORKERS = "1"
  COOKIES_FILE = "/app/yt-dlp-cache/cookies.txt"
  YTDLP_CACHE_DIR = "/app/yt-dlp-cache"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "ytdlp_cache"
  destination = "/app/yt-dlp-cache"
